### ISSUE TITLE
I'm getting "fail to import" when trying define as user language

### ISSUE THREAD

**Issue by Linnshet** [jNizM/ahk_notepad-plus-plus#11]
Title. Something in a new update must be messing with it, I assume?

**Comment by ReinoWCC** [comment]
Downloading it as "save as" doesn't work. You have to download the file, and paste in the raw code like from here "https://raw.githubusercontent.com/jNizM/ahk_notepad-plus-plus/master/userDefineLang/lazy/userDefineLang_AHK.xml" Trying to do save as from the website, just saves the webpage it goes to.

**Comment by jNizM** [comment]
Works as he described.
