### ISSUE TITLE
v2 quoted strings

### ISSUE THREAD

**Issue by Lexikos** [jNizM/ahk_notepad-plus-plus#12]
Currently quoted strings are defined only as `"` start and end, so the following v2-specific strings are not highlighted correctly:
```
x := "Say `"hello`""
x := 'Say "hello"'
```

**Comment by jNizM** [comment]
![grafik](https://user-images.githubusercontent.com/2289812/208443741-bff87950-0571-495f-a811-18092bfbeed5.png)

'string' is now added.
I can also color the hello in the first example green. But I don't currently know how to recolor the escape string inside a string with UDL2 like in vscode.

**Comment by Lexikos** [comment]
I don't think it's designed to colour escape sequences differently to the string, but you should at least define the escape character so that an escaped quote doesn't terminate the string. In the GUI it's a simple matter of setting the *Escape* under *Operators & Delimiters*.
