### ISSUE TITLE
Explain the difference between "Default Theme" and "Lazy Theme"

### ISSUE THREAD

**Issue by Stevoisiak** [jNizM/ahk_notepad-plus-plus#2]
I'm a bit confused what the difference is between the "Default Theme" and "Lazy Theme".

While the screenshots are helpful, the naming scheme is a bit confusing.  Does the Lazy Theme have anything to do with [Lazy Evaluation](https://en.wikipedia.org/wiki/Lazy_evaluation)?

It would be helpful if an explanation were [added to the Readme](https://github.com/jNizM/ahk_notepad-plus-plus/blob/master/README.md).

**Comment by jNizM** [comment]
Hey "default theme" was created by an ahk member and the "lazy theme" was borrowed by Sublime Text Editor. Both are color themes and you can see the difference if you click on preview.

**Comment by Stevoisiak** [comment]
@jNizM I'm specifically curious as to why it was called the "Lazy Theme". Is there a reason behind the name?

**Comment by jNizM** [comment]
It's just a name like "sunburst" theme
