### ISSUE TITLE
AutoComplete Instructions is Incorrect

### ISSUE THREAD

**Issue by amiga-500** [jNizM/ahk_notepad-plus-plus#5]
The front page says: 

> Save it to the right location (C:\Program Files (x86)\Notepad++\plugins\APIs\AutoHotkey.xml)

At least as of v7.7 this should read:

> Save it to the right location (C:\Program Files (x86)\Notepad++\autoCompletion\AutoHotkey.xml)

**Comment by jNizM** [comment]
Updated Readme

**Comment by Saya47** [comment]
Are you sure the new location is correct? I didn't have the folder `autoCompletion` I created it and it didn't work.
Moved it to `plugins\APIs\` and it worked!

**Comment by jNizM** [comment]
Notepad++ 8.3 (x64)
This folder is present by default with the installation.
![Screenshot 2022-02-10 093829](https://user-images.githubusercontent.com/2289812/153369387-87fb5014-91de-4d39-a3bd-c2d6ebd54494.png)
