### ISSUE TITLE
userDefineLang_AHK.xml "Fail to import."

### ISSUE THREAD

**Issue by cds5296** [jNizM/ahk_notepad-plus-plus#6]
Like the title says, userDefineLang_AHK.xml "Fail to import." when trying to import.

Notepad++ v7,9,1   64-bit

**Comment by GamenRoll** [comment]
me neither
Notepad++ v7,9,1 64-bit

**Comment by jNizM** [comment]
works for me as expected (7.9.5)
download the raw file and not copy-past from github page

**Comment by jNizM** [comment]
Updated and tested for N++ v8.1
