### ISSUE TITLE
[Minor Discrepancy] Forum Post VS GitHub README  

### ISSUE THREAD

**Issue by gamepad-coder** [jNizM/ahk_notepad-plus-plus#8]
First off, I've been using this for years and I'm a huge fan of this repo.  
So thanks a million for this!

## Minor Issue:

GitHub README.md lists Auto-Complete folder as:
- `C:\Program Files\Notepad++\autoCompletion\`
- https://github.com/jNizM/ahk_notepad-plus-plus

Forum Post lists Auto-Complete folder as:
- `C:\Program Files\Notepad++\plugins\APIs\`
- https://www.autohotkey.com/boards/viewtopic.php?t=50

Using a fresh PC install & the GitHub instructions worked seamlessly, but I haven't tried using the `\plugins\APIs\` folder for years, so unsure if this still works.

Just wanted to bring this to your attention.

## &nbsp;

_I've enjoyed countless hours in Notepad++ while using this language pack. And it's half the reason I began using AutoHotkey so frequently in the first place._

_So again, thank you so much for this._

**Comment by jNizM** [comment]
Forum Manual is fixed. Also it is updated and tested for N++ v8.1
